settings:
  title: 'Status Page'
  url: 'https://status.lilyfeather.es' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Todos los sistemas operativos'
  notAllmonitorsOperational: 'Algunos servicios no están operativos'
  monitorLabelOperational: 'Operativo'
  monitorLabelNotOperational: 'No operativo'
  monitorLabelNoData: 'Sin datos'
  dayInHistogramNoData: 'Sin datos'
  dayInHistogramOperational: 'Todo correcto'
  dayInHistogramNotOperational: ' incidente(s)' # xx incident(s) recorded

monitors:
  - id: odiseageek # unique identifier
    name: Odisea Geek
    description: 'Blog personal. Jekyll hosteado en GitHub Pages' # default=empty
    url: 'https://odiseageek.es/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: lf-files
    name: Nextcloud
    description: 'Archivos en la nube'
    url: 'https://files.lilyfeather.es'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    followRedirect: true

  - id: lf-dav
    name: Baïkal
    description: Calendario y contactos
    url: 'https://dav.lilyfeather.es'
    method: GET
    expectStatus: 200
    followRedirect: true


  - id: lf-calibre
    name: Calibre
    description: Biblioteca virtual
    url: 'https://books.lilyfeather.es'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: lf-dav
    name: Bloben
    description: Cliente web para el calendario
    url: 'https://calendar.lilyfeather.es'
    method: GET
    expectStatus: 200
    followRedirect: true

